name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  web_build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - name: "Web Build 🔧"
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release
      - name: "Web Deploy 🚀"
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: '${{ secrets.tyy_tools }}'
          branch: gh-pages
          folder: build/web